Rails.application.routes.draw do
  root 'examples#home'
  get 'drum', to: 'examples#drum'
  get 'clock', to: 'examples#clock'
  get 'CSSVar', to: 'examples#CSSVar'
  get 'arrays', to: 'examples#arrays'
  get 'flex', to: 'examples#flex'
  get 'search', to:'examples#search'
  get 'arrays2', to: 'examples#arrays2'
  get 'canvas', to: 'examples#canvas'
  get 'checkbox', to: 'examples#checkbox'
  get 'video', to: 'examples#video'
  get 'detection', to: 'examples#detection'
  get 'slide', to: 'examples#slide'
  get 'storage', to: 'examples#storage'
  get 'shadow', to: 'examples#shadow'
  get 'bands', to: 'examples#bands'
  get 'times', to: 'examples#times'
  get 'cam', to: 'examples#cam'
  get 'speech', to: 'examples#speech'
  get 'location', to: 'examples#location'
end
